/**
 * Compiles the TS token source (src/tokens) into generated CSS custom
 * properties. Never hand-edit the output files in src/theme/generated/ —
 * edit src/tokens/*.ts and re-run `npm run build:tokens`.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  color,
  space,
  radius,
  shadow,
  font,
  motion,
  zIndex,
  lightColorTokens,
  darkColorTokens,
  type SemanticColorTokens,
} from "../src/tokens";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "../src/theme/generated");
mkdirSync(outDir, { recursive: true });

const HEADER = `/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */\n`;

function toKebab(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function flatten(prefix: string, obj: Record<string, unknown>): string[] {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const varName = `--dym-${prefix}-${toKebab(key)}`;
    if (typeof value === "object" && value !== null) {
      lines.push(...flatten(`${prefix}-${toKebab(key)}`, value as Record<string, unknown>));
    } else {
      lines.push(`  ${varName}: ${value};`);
    }
  }
  return lines;
}

// ---- base.css: theme-independent primitive + scale tokens ----
const baseLines = [
  ...flatten("color", color),
  ...flatten("space", space),
  ...flatten("radius", radius),
  ...flatten("shadow", shadow),
  ...flatten("font", font),
  ...flatten("motion", motion),
  ...flatten("z", zIndex),
];

writeFileSync(
  resolve(outDir, "base.css"),
  `${HEADER}:root {\n${baseLines.join("\n")}\n}\n`,
);

// ---- light.css / dark.css: semantic color tokens ----
function semanticBlock(tokens: SemanticColorTokens): string {
  return Object.entries(tokens)
    .map(([key, value]) => `  --dym-color-${key}: ${value};`)
    .join("\n");
}

writeFileSync(
  resolve(outDir, "light.css"),
  `${HEADER}:root,\n[data-theme="light"] {\n${semanticBlock(lightColorTokens)}\n}\n`,
);

writeFileSync(
  resolve(outDir, "dark.css"),
  `${HEADER}[data-theme="dark"] {\n${semanticBlock(darkColorTokens)}\n}\n\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${semanticBlock(
      darkColorTokens,
    )
      .split("\n")
      .map((l) => `  ${l}`)
      .join("\n")}\n  }\n}\n`,
);

console.log("Tokens compiled to src/theme/generated/{base,light,dark}.css");
